In [1]:
import numpy as np
import pandas as pd
from scipy.linalg import eig
movies_df = pd.read_csv(r"C:\Users\akgh1\Desktop\movies.csv")

ratings_df = pd.read_csv(r"C:\Users\akgh1\Desktop\ratings.csv")
ratings_df

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [3]:
movies_df["title"].values[855]

'Drop Dead Fred (1991)'

In [4]:
movies_df

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [6]:
dic[0]

1

In [5]:
dic = {}
for i in range(9742):
    dic[i] = movies_df['movieId'][i]
dic[9741]

193609

In [45]:
df = np.loadtxt("S.txt")
df

array([[4. , 0. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [2.5, 2. , 2. , ..., 0. , 0. , 0. ],
       [3. , 0. , 0. , ..., 0. , 0. , 0. ],
       [5. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [48]:
len(np.dot(df.T , df))

9742

In [6]:
# df = np.loadtxt("myarray.txt")
# df

array([[4., 0., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [2., 2., 2., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

In [46]:
def svd(matrix, k=None):
    """
    Perform Singular Value Decomposition (SVD) on the given matrix.

    Parameters:
    - matrix: The input matrix to decompose.
    - k: The number of singular values to retain. If None, all singular values are retained.

    Returns:
    U, Sigma, Vt: Matrices from the decomposition.
    """
    # Step 1: Compute covariance matrices
    M = np.dot(matrix, matrix.T)
    N = np.dot(matrix.T, matrix)

    # Step 2: Compute eigenvalues and eigenvectors
    eigenvalues_M, U = np.linalg.eigh(M)
    print(eigenvalues_M)
    eigenvalues_N, Vt = np.linalg.eigh(N)
  
    # Step 3: Sort eigenvalues and eigenvectors in descending order
    # U = U[:, ::-1]
    # Sort the eigenvalues in descending order
    sorted_indices = np.argsort(eigenvalues_N)[::-1]
    eigenvalues_N = eigenvalues_N[sorted_indices]
    Vt = Vt[:, sorted_indices]
    # Vt = Vt[:, ::-1]
    sorted_indices = np.argsort(eigenvalues_M)[::-1]
    eigenvalues_M = eigenvalues_M[sorted_indices]
    print(eigenvalues_M)
    # print(eigenvalues_N)
    j=[]
    # Compute the singular values
    # singular_values = np.sqrt(eigenvalues)
    p = 0
    for i in range(len(eigenvalues_N)):
        if eigenvalues_N[i] == 0 or eigenvalues_N[i] < 0:
            p = i
            break
    
    for i in range(len(eigenvalues_N)):
        if eigenvalues_N[i] != 0 :
            j.append(eigenvalues_N[i])
    r = len(j)
    print(" r= " , r)
    no_zero = np.array(j)
    no_zero = np.sqrt(no_zero)
    print(no_zero)
    U = U[:, sorted_indices]
    # eigenvalues_M = eigenvalues_M[::-1]

    # Step 4: Compute singular values (square root of eigenvalues)
    # singular_values = np.sqrt(eigenvalues_N)
    # Sigma = np.diag(singular_values)

    Sigma = no_zero[~np.isnan(no_zero)]

    # Sigma = np.sqrt(eigenvalues_M)

    # Step 5: Truncate matrices based on the specified number of singular values (k)
    if k is not None:
        U = U[:, :k]
        Sigma = Sigma[:k]
        Vt = Vt[:k, :]

    return U[: , :p], Sigma, Vt[: , :p].T


In [58]:
import numpy as np

def power_iteration(matrix, num_iterations):
    # Initialize a random vector
    vector = np.ones(len(matrix))

    for _ in range(num_iterations):
        # Multiply the matrix by the vector
        matrix_vector_product = np.dot(matrix, vector)

        # Normalize the result
        vector = matrix_vector_product / np.linalg.norm(matrix_vector_product)

    # Calculate the eigenvalue
    eigenvalue = np.dot(matrix_vector_product, vector)

    return eigenvalue, vector

def eigen_decomposition(A, num_iterations=4):
    n = len(A)
    eigenvalues = np.zeros(n)
    eigenvectors = np.zeros((n, n))
    
    for i in range(n):
        # Use power iteration to find eigenvalue and eigenvector
        eigenvalue, eigenvector = power_iteration(A, num_iterations)
        # eigenvalue *=10
        # Store the results
        eigenvalues[i] = eigenvalue
        eigenvectors[:, i] = eigenvector
    
        # Deflate the matrix to find the next eigenvalue
        print("mamad")
        print(np.outer(eigenvector, eigenvector))
        # A = A - eigenvalue * np.outer(eigenvector, eigenvector)
        A = A - np.dot(eigenvalue , np.dot(eigenvector, eigenvector))
    return eigenvalues, eigenvectors


# Example usage
# matrix = np.array([
#     [4, -1],
#     [2,  1]
# ])
matrix = np.array([[4, 11 , 14],
                   [8, 7 , -2]])
# # matrix = np.array([[1, -1],
# #               [-2, 2],
# #               [2, -2]])
matrix = np.dot(matrix.T , matrix)
# matrix = np.dot(df.T , df)
# eigenvalue, eigenvector = power_iteration(matrix, num_iterations=1000)
eigenvalues, eigenvectors = eigen_decomposition(matrix)
for i in range(0 , len(eigenvalues)):
    eigenvalues[i] = round(eigenvalues[i], 2)
print("Eigenvalue:", eigenvalues)
print("Eigenvector:", eigenvectors)


mamad
[[0.11145854 0.22265625 0.22239543]
 [0.22265625 0.44479146 0.44427043]
 [0.22239543 0.44427043 0.44375   ]]
mamad
[[0.43140897 0.34041927 0.35973601]
 [0.34041927 0.26862046 0.28386305]
 [0.35973601 0.28386305 0.29997057]]
mamad
[[0.35894416 0.33732288 0.34105208]
 [0.33732288 0.31700398 0.32050855]
 [0.34105208 0.32050855 0.32405186]]
Eigenvalue: [ 360.    751.97 3001.52]
Eigenvector: [[0.33385406 0.65681731 0.59911949]
 [0.66692688 0.51828608 0.56303107]
 [0.66614563 0.54769569 0.56925553]]


In [ ]:
def svd(A, eigenvalues , V):

    # Sort the eigenvalues in descending order
    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_indices]
    V = V[:, sorted_indices]
    # Compute the singular values
    for eigen_value in eigenvalues:
        if eigen_value > 0:
            singular_values = np.sqrt(eigenvalues)

    # Compute the matrix U
    U = np.dot(A, V)
    print(U)

    num_positive_singular = len(singular_values)
    
    U[: , :num_positive_singular] /= singular_values
    
    # Create the diagonal matrix Σ
    Sigma = np.diag(singular_values)
    
    return U[: , :num_positive_singular], Sigma, V[:, :num_positive_singular].T

In [9]:
U, Sigma, Vt = svd(A)
print( U) 
print(" ")
print("___________________________________________________________________________")
print(Sigma) 
print(" ")
print("___________________________________________________________________________")
print(Vt)
print("___________________________________________________________________________")
# ss = np.dot(U , Sigma)
# print(np.dot(ss,Vt))

[ 90. 360.]
[360.  90.]
 r=  3
[18.97366596  9.48683298         nan]
[[-0.9486833   0.31622777]
 [-0.31622777 -0.9486833 ]]
 
___________________________________________________________________________
[18.97366596  9.48683298]
 
___________________________________________________________________________
[[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]
___________________________________________________________________________


C:\Users\akgh1\AppData\Local\Temp\ipykernel_17888\4161745378.py:47: RuntimeWarning: invalid value encountered in sqrt
  no_zero = np.sqrt(no_zero)


In [210]:
Un, S, V = np.linalg.svd(df)
print( U) 
print(" ")
print("___________________________________________________________________________")
print(S) 
print(" ")
print("___________________________________________________________________________")
print(V)
print("___________________________________________________________________________")
# ss = np.dot(U , S)
# print(np.dot(ss,V))

[[-5.87345305e-02  6.21026505e-02 -3.49542008e-03 ...  2.97456408e-03
  -2.10156653e-04  3.39456818e-04]
 [-5.78779114e-03 -1.75595387e-02 -4.82222499e-03 ... -3.16470381e-03
  -8.42336637e-03  7.32719887e-04]
 [-1.04449527e-03  1.60451128e-03  1.54613096e-03 ... -2.23215056e-03
  -2.54491467e-03 -1.84948611e-03]
 ...
 [-1.13309443e-01  3.55645722e-03 -8.97055798e-03 ...  1.25486545e-03
  -5.09102366e-04  1.34914595e-03]
 [-8.06446379e-03  1.51896718e-02 -4.13018274e-02 ...  1.12256696e-02
  -4.14863382e-03 -1.77216763e-02]
 [-1.36649651e-01 -2.01098587e-01  7.35214792e-02 ... -1.19085693e-04
  -4.22901430e-04  7.43794860e-04]]
 
___________________________________________________________________________
[511.66576176 223.84355603 187.22055486 163.96610293 149.42576459
 141.96179148 129.7585341  118.48894988 116.53481388 108.15042669
 105.04111753 103.61746881 101.94929334  97.00537043  95.48909396
  95.29604573  91.76680298  90.67672863  89.35954452  88.18959731
  87.53033315  85.5096

In [329]:
def top_cosine_similarity(U, data, movie_id, top_n=10):
    index = movie_id - 1 # Movie id starts from 1
    user_row = U[index, :]
    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))
    similarity = np.dot(user_row, data.T) / (magnitude[index] * magnitude)
    sort_indexes = np.argsort(-similarity)
    print(similarity.shape)
    print(sort_indexes , sort_indexes.max())
    return sort_indexes[:top_n]

In [338]:
k = 610
movie_id = 1 # Grab an id from movies.dat
top_n = 10

sliced = V.T[:, :k] # representative data
print(sliced.shape)
indexes = top_cosine_similarity(Un, sliced, movie_id, top_n)
# print_similar_movies(movie_data, movie_id, indexes)

(9742, 610)
(9742,)
[1126 1332 2788 ... 9590 6503 9117] 9741


C:\Users\akgh1\AppData\Local\Temp\ipykernel_21184\4166208365.py:5: RuntimeWarning: invalid value encountered in divide
  similarity = np.dot(user_row, data.T) / (magnitude[index] * magnitude)


In [339]:
indexes

array([1126, 1332, 2788, 2182, 1326,  927, 1505, 1517, 1110, 1994],
      dtype=int64)

In [340]:
for i in indexes:
    # try:
    print(movies_df["title"].values[dic[i]])


Exorcist II: The Heretic (1977)
Rambo III (1988)
Royal Wedding (1951)
Bring It On (2000)
Jack Frost (1998)
U Turn (1997)
Autumn Tale, An (Conte d'automne) (1998)
Killer's Kiss (1955)
Breakfast Club, The (1985)
Caddyshack (1980)


In [341]:
for i in indexes:
    # try:
    print(movies_df[movies_df["movieId"] == dic[i]].title.values[0])

Best Men (1997)
Newton Boys, The (1998)
Shaft (1971)
Gulliver's Travels (1939)
Welcome to Woop-Woop (1997)
Quiet Man, The (1952)
Black Cauldron, The (1985)
Great Mouse Detective, The (1986)
McHale's Navy (1997)
Wolf Man, The (1941)


###########################################################################################################

In [330]:
k = 610
movie_id = 1 # Grab an id from movies.dat
top_n = 10

sliced = Vt.T[:, :k] # representative data
print(sliced.shape)
indexes = top_cosine_similarity(U, sliced, movie_id, top_n)

(9742, 610)
(9742,)
[ 735 6667 4169 ... 8228 9693 8143] 9741


C:\Users\akgh1\AppData\Local\Temp\ipykernel_21184\4166208365.py:5: RuntimeWarning: invalid value encountered in divide
  similarity = np.dot(user_row, data.T) / (magnitude[index] * magnitude)


In [332]:
indexes

array([ 735, 6667, 4169, 6090, 3113,  765, 7217, 7673, 6749, 2242],
      dtype=int64)

In [337]:
for i in indexes:
    # try:
    print(movies_df[movies_df["movieId"] == dic[i]].title.values[0])
    # print(movies_df["title"].values[dic[i]])


Bringing Up Baby (1938)
Cat Soup (Nekojiru-so) (2001)
Confessions of a Dangerous Mind (2002)
Rumor Has It... (2005)
Lilies of the Field (1963)
Apple Dumpling Gang, The (1975)
American Pie Presents: The Book of Love (American Pie 7: The Book of Love) (2009)
Hesher (2010)
American Pie Presents Beta House (American Pie 6: Beta House) (2007)
Crazy in Alabama (1999)
